apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-summary
spec:
  replicas: 1
  selector:
    matchLabels:
      name: url-summary
  template:
    metadata:
      labels:
        name: url-summary
    spec:
      containers:
        - name: url-summary
          image: ghcr.io/rassi0429/url-summary:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
            - name: PORT
              value: {{ .Values.env.APP_TARGET_PORT | quote }}
            - name: CORS
              value: {{ .Values.env.CORS | quote }}
---
kind: Service
apiVersion: v1
metadata:
  name: url-summary-lb
spec:
  selector:
    name: url-summary
  ports:
    - protocol: TCP
      port: {{ .Values.LB_LISTEN_PORT }}
      targetPort: {{ .Values.env.APP_TARGET_PORT }}
  type: LoadBalancer
