apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: { .Values.storageClassName | quote }