apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: misskey-exporter
  template:
    metadata:
      labels:
        name: misskey-exporter
    spec:
      containers:
        - name: misskey-exporter
          image: ghcr.io/rassi0429/misskey-exporter:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
            - name: instance
              value: {{ .Values.INSTANCE | quote }}
---
kind: Service
apiVersion: v1
metadata:
  name: misskey-exporter-lb
spec:
  selector:
    name: misskey-exporter
  ports:
    - protocol: TCP
      port: {{ .Values.LB_LISTEN_PORT }}
      targetPort: {{ .Values.APP_TARGET_PORT }}
  type: {{ .Values.LB_TYPE }}
